name: tahoe-scorm tests

on: push

jobs:
  build:
    strategy:
      matrix:
        python-versions: [2.7, 3.5, 3.8]
        containers: [python:2.7.18-buster, python:3.5.10-buster, python:3.8.12-buster]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.tox-env }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install dependencies
        run: |
          pip install tox
      - name: Run tox
        run: |
          tox
    container: ${{ matrix.containers }}